import datetime

from airflow.decorators import dag, task

markdown_text = """
### Train Student Performance

Trains a Logistic Regression model on the latest ETL output (S3),
searches hyperparameters with Optuna, and registers the model in
MLflow. Promotes it to `champion` alias if it beats the current one
by weighted F1.

Triggered automatically by `process_etl_student_performance` when the
dataset changes, or manually.
"""

default_args = {
    "owner": "Grupo 10",
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": datetime.timedelta(minutes=5),
}


@dag(
    dag_id="train_student_performance",
    description="Train and register the Student Performance model.",
    doc_md=markdown_text,
    default_args=default_args,
    schedule=None,
    catchup=False,
    tags=["Training", "Student Performance"],
)
def train_student_performance():

    @task.virtualenv(
        requirements=["boto3"],
        system_site_packages=True,
    )
    def get_latest_dataset() -> str:
        "Return the latest Student Performance dataset folder from MinIO."
        import os
        import boto3

        # Connect to MinIO using S3-compatible credentials
        s3 = boto3.client(
            "s3",
            endpoint_url=os.getenv("AWS_ENDPOINT_URL_S3"),
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
        )

        # List all available Student Performance dataset folders
        response = s3.list_objects_v2(
            Bucket="data",
            Prefix="student_performance/",
            Delimiter="/",
        )

        folders = [
            item["Prefix"].rstrip("/").split("/")[-1]
            for item in response.get("CommonPrefixes", [])
        ]

        if not folders:
            raise ValueError("No Student Performance datasets found in MinIO.")

        # Dataset folders are timestamped, so max() returns the latest one
        latest_folder = max(folders)
        print(f"Latest dataset: {latest_folder}")

        return latest_folder

    @task.virtualenv(
        requirements=[
            "awswrangler==3.6.0",
            "scikit-learn==1.9.0",
            "mlflow==2.10.1",
            "optuna>=4.0.0",
            "numpy<2",
        ],
        system_site_packages=True,
    )
    def train_model(dataset_folder: str) -> None:
        "Train, evaluate and register the Student Performance model."
        import awswrangler as wr
        import mlflow
        import mlflow.sklearn
        import numpy as np
        import optuna

        from mlflow.models import infer_signature
        from sklearn.linear_model import LogisticRegression
        from sklearn.metrics import (
            accuracy_score,
            f1_score,
            precision_score,
            recall_score,
        )
        from sklearn.model_selection import cross_val_score

        # Load the train/test datasets generated by the ETL
        base_path = f"s3://data/student_performance/{dataset_folder}"

        X_train = wr.s3.read_csv(f"{base_path}/X_train.csv")
        X_test = wr.s3.read_csv(f"{base_path}/X_test.csv")
        y_train = wr.s3.read_csv(f"{base_path}/y_train.csv").squeeze("columns")
        y_test = wr.s3.read_csv(f"{base_path}/y_test.csv").squeeze("columns")

        print(f"Train shape: {X_train.shape}")
        print(f"Test shape: {X_test.shape}")

        # Configure the MLflow experiment
        mlflow.set_tracking_uri("http://mlflow:5000")
        experiment = mlflow.set_experiment("Student Performance - Training")

        # Optuna tries different hyperparameters and maximizes weighted F1
        def objective(trial):
            C = trial.suggest_float("C", 1e-4, 1e2, log=True)
            solver = trial.suggest_categorical("solver", ["lbfgs", "saga"])

            model = LogisticRegression(
                C=C,
                solver=solver,
                max_iter=1000,
                random_state=42,
            )

            score = cross_val_score(
                model,
                X_train,
                y_train,
                cv=5,
                scoring="f1_weighted",
            ).mean()

            return float(score)

        # One MLflow run contains the full training process
        with mlflow.start_run(
            experiment_id=experiment.experiment_id,
            run_name=f"training_{dataset_folder}",
        ):
            # Search for the best Logistic Regression hyperparameters
            study = optuna.create_study(direction="maximize")
            study.optimize(objective, n_trials=10)

            print(f"Best parameters: {study.best_params}")
            print(f"Best CV F1: {study.best_value:.4f}")

            # Train the final model using the best parameters
            model = LogisticRegression(
                **study.best_params,
                max_iter=1000,
                random_state=42,
            )

            model.fit(X_train, y_train)

            # Evaluate the model on the test set
            y_pred = model.predict(X_test)

            metrics = {
                "accuracy": accuracy_score(y_test, y_pred),
                "f1_weighted": f1_score(
                    y_test,
                    y_pred,
                    average="weighted",
                ),
                "precision_weighted": precision_score(
                    y_test,
                    y_pred,
                    average="weighted",
                    zero_division=0,
                ),
                "recall_weighted": recall_score(
                    y_test,
                    y_pred,
                    average="weighted",
                    zero_division=0,
                ),
                "best_cv_f1": study.best_value,
            }

            # Log parameters and metrics to MLflow
            mlflow.log_param("model", "LogisticRegression")
            mlflow.log_param("dataset_folder", dataset_folder)
            mlflow.log_params(study.best_params)
            mlflow.log_metrics(metrics)

            # Link al preprocesador de este dataset (trazabilidad)
            preprocessor_path = f"{base_path}/etl_preprocessor.pkl"
            mlflow.log_param("preprocessor_s3_path", preprocessor_path)

            # Register the trained model in the MLflow Model Registry
            signature = infer_signature(
                X_train,
                model.predict(X_train),
            )

            # Registrar el modelo (crea una version nueva)
            signature = infer_signature(
                X_train,
                model.predict(X_train),
            )

            model_name = "student_performance_model"

            mlflow.sklearn.log_model(
                sk_model=model,
                artifact_path="model",
                registered_model_name=model_name,
                signature=signature,
            )

            # Buscar la version recien creada, filtrando por el run actual
            current_run_id = mlflow.active_run().info.run_id
            client_versions = mlflow.MlflowClient().search_model_versions(
                f"run_id='{current_run_id}'"
            )
            new_version = client_versions[0].version
            new_f1 = metrics["f1_weighted"]

            # Comparar contra el champion actual, si existe
            client = mlflow.MlflowClient()

            try:
                champion = client.get_model_version_by_alias(model_name, "champion")
                champion_run = client.get_run(champion.run_id)
                champion_f1 = champion_run.data.metrics.get("f1_weighted", 0)
            except Exception:
                # No hay champion todavia: este modelo lo es por default
                champion_f1 = None

            if champion_f1 is None or new_f1 > champion_f1:
                client.set_registered_model_alias(model_name, "champion", new_version)
                print(f"New champion: v{new_version} (f1={new_f1:.4f})")
            else:
                print(f"Challenger v{new_version} (f1={new_f1:.4f}) did not beat champion (f1={champion_f1:.4f})")

    # DAG dependency: first find the latest dataset, then train the model
    latest_dataset = get_latest_dataset()
    train_model(latest_dataset)


dag = train_student_performance()