[project]
name = "notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "awswrangler>=3.17.0",
    "ipykernel>=7.3.0",
    "mlflow>=3.14.0",
    "numpy<2",
    "optuna>=4.9.0",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "sweetviz>=2.3.3",
]
